import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Snaketter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Snaketter</a>
        </h1>
        <nav className='nav'>
        <Link href='/timeline'>timeline</Link>
        </nav>
        

        </main>
    </div>
  )
}

export default Home;
